# After change language files you need change once config file or restart/reload server to reload the language files.

# Monitor config file change/delete and reload/release config file.
fileWatchService: true

# Settings
settings:
  # When debug is true, plugin will output debug message.
  debug: false
  # Continuous update the entity health display.
  continuousUpdate:
    # If it's true then the entity health display is continuous update, rather than update once
    enable: true
    # Duration time(second(s))(When the entity dead it will be terminated).
    duration: 5
    # Periodic intervals(ms)(Update frequency).
    period: 100
  # If it's true then the entity list is blacklist rather than whitelist
  isBlacklist: true
  # Entity list (Case sensitive(Maybe)
  entityList:
    - XP_ORB

# Message
message:
  # Text
  text: '{{entityName}}§7: [§r{{healthNotEmpty}}{{healthEmpty}}§7]§r §r{{healthNum}}§7/§r{{healthNumMax}}§r'
  # Health bar length
  healthBarLength: 10
  # Health bar not empty part
  healthBarNotEmpty: '§c❤§r'
  # Health bar empty part
  healthBarEmpty: '§8❤§r'
  # Decimal places of health number display
  healthNumDecimalPlaces: 2